spring:
  application:
    name: netflix-eureka-naming-server
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service:
      waitTimeInMsWhenSyncEmpty: 0

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  #service will be mapped under the /api uri
  prefix: /api
  routes:
    categorie:
      path: /categorie/**
      url: http://categorie:6082
    projet:
      path: /projet/**
      url: http://projet:8081
    commentaire:
      path: /commentaire/**
      url: http://commentaire:8083
    censure:
      path: /censure/**
      url: http://censure:8089
    debat:
      path: /debat/**
      url: http://debat:8088
    debatuc:
      path : /debatuc/**
      url: http://debatuc:8095
    like:
      path: /like/**
      url: http://like:8085
    media:
      path: /media/**
      url: http://media:8086
    note:
      path: /note/**
      url: http://note:8084
    notification:
      path: /notification/**
      url: http://notification:8092
    preference:
      path: /preference/**
      url: http://preference:8090
    programme:
      path: /programme/**
      url: http://programme:8091
    sondage:
      path: /sondage/**
      url: http://sondage:7087
    stats:
      path: /stats/**
      url: http://stats:6093
    user:
      path: /users/**
      url: http://user:6087

ribbon:
  readTimeout: 5000
  connectTimeout: 5000